name: Workflow
on:
  push:
    branches:
      - sec-test

jobs:
  SAST:
    runs-on: ubuntu-24.04

    steps:
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '18'

      - name: Respuesta
        run: |
          echo "Instalado"
