name: Workflow
on:
  push:
    branches:
      - sec-test

jobs:
  SAST:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set Environment Variables
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

        #LINEAS DE VALIDACION
      - name: Variable
        run: echo "$BRANCH_NAME"

      - name: Valida variable sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -f "package.json" ]; then
            echo "archivo package.json encontrado"
            echo "verificando conf plugin sonar"
            if ! grep -q '"sonar-scanner"' package.json; then
              echo "No se encontro dependencia"
              npm cache clean --force
              npm install --save-dev sonar-scanner
              echo "dependencia instalada"
              cat package.json
            else
              echo "dependencia ya esta instalada"
            fi
          else
            echo "no se encontro archivo package.json"
            exit 1
          fi